accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'^signup/$',views.SignUp.as_view(),name='signup'),
]

tutorportal/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

import misaka
# Create your models here.

from django.contrib.auth import get_user_model

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html = misaka_html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

accounts/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView
from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm

    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

posts/views.py
from django.shortcuts import render

# Create your views here.

tutorportal/views.py
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = "index.html"

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Log In</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Log In">
  </form>

</div>

{% endblock  %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Sign Up</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Sign Up">
  </form>

</div>

{% endblock  %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>TutorPortal</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'tutorportal/css/master.css'%}">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mynav" role='navigation' id="navbar">
      <div class="container-fluid">
        <a class="navbar-brand mynav" href="{% url 'home' %}">TutorPortal</a>
        <ul class="navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li class="nav-item active"><a class="nav-link" href="#">Create Post</a></li>
            <li class="nav-item"><a class="nav-link" href="#">My Posts</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a></li>

          {% else %}
            <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:login' %}">Log In</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}

        </ul>
      </div>

    </nav>

    <div class="container mycontent">
      {% block content %}

      {% endblock  %}
    </div>


  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

  <h1>Welcome to TutorPortal</h1>

{% endblock  %}

templates/test.html
{% extends "base.html" %}

{% block content %}
  <h1>You are now logged in!</h1>
{% endblock  %}

templates/thanks.html
{% extends "base.html" %}

{% block content %}
  <h1>Thanks for visiting! Comeback soon...</h1>
{% endblock  %}